{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xatu-sentry-logs.fullname" . }}-vector
  labels:
    {{- include "xatu-sentry-logs.labels" . | nindent 4 }}
data:
  vector.yaml: |-
    {{- tpl .Values.config $ | nindent 4 }}
{{- end }}
