{{- if and .Values.ingress.enabled .Values.ingress.basicAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powfaucet.fullname" . }}-basic-auth
  labels:
    {{- include "powfaucet.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth: {{ .Values.ingress.basicAuth | quote }}
{{- end }}
